export const environment = {
  SERVER_URL: `./`,
  BASE_API_URL: 'http://localhost:8310/',
  BASE_UPLOAD_URL: 'https://localhost:44375/api/server-upload/upload',
  BASE_FILE_URL: 'https://localhost:44375/Resources/Images/',
  ALLOW_ANONYMOUS: '?_allow_anonymous=true',
  production: true,
  useHash: true,
  hmr: false,
  pro: {
    theme: 'light',
    menu: 'side',
    contentWidth: 'fluid',
    fixedHeader: true,
    autoHideHeader: true,
    fixSiderbar: true,
    onlyIcon: false,
    colorWeak: false,
  },
};
